#!/usr/bin/env python3
"""Regenerate the README results table from a benchmark summary CSV.

The README claims that every cell in its results table comes from the benchmark CSV and that
nothing is typed in by hand. This script is what makes that claim true. It reads a summary CSV
written by BenchmarkRunner, rewrites the region between the marker comments in the README, and
prints what it did.

    python tools/update_readme_table.py --csv results/<file>.csv [more.csv ...]

Standard library only, by design: the evidence pipeline should not need a package install to run.

Method (see docs/METHOD.md):
  * Only release player rows are eligible. Editor rows, batch-mode rows and development-build rows
    are refused, because they do not measure the same program. --allow-editor overrides this for
    inspection, and stamps the table as ineligible.
  * A data point is one (agent_count, techniques) group. Its runs are summarised as the median of
    the per-run medians, plus the min and max of those per-run medians so run-to-run spread is
    visible rather than hidden.
  * Medians and percentiles use nearest rank -- the same definition as Percentiles.NearestRank in
    the C# harness -- so a printed value is always a value that was actually measured, never an
    interpolation between two.
  * Nothing is estimated. A quantity that was not measured prints as an empty cell.
"""

from __future__ import annotations

import argparse
import csv
import math
import sys
from pathlib import Path

TABLE_BEGIN = "<!-- RESULTS_TABLE:BEGIN -->"
TABLE_END = "<!-- RESULTS_TABLE:END -->"
BUDGET_BEGIN = "<!-- BUDGET_CROSSING:BEGIN -->"
BUDGET_END = "<!-- BUDGET_CROSSING:END -->"

BUDGET_60_MS = 1000.0 / 60.0
BUDGET_30_MS = 1000.0 / 30.0

GENERATED_NOTE = (
    "*Generated by `tools/update_readme_table.py` from `{csv}` — do not edit by hand.*"
)


def nearest_rank(sorted_values: list[float], p: float) -> float:
    """Percentile by nearest rank: index ceil(p*n)-1 of the sorted samples.

    Matches Percentiles.NearestRank in the C# harness. Never averages two samples, so the result
    is always an observed value.
    """
    n = len(sorted_values)
    if n == 0:
        raise ValueError("no samples")
    rank = max(1, min(n, math.ceil(p * n)))
    return sorted_values[rank - 1]


def median(values: list[float]) -> float:
    return nearest_rank(sorted(values), 0.5)


def fnum(value: float | None, places: int = 2) -> str:
    if value is None:
        return ""
    return f"{value:.{places}f}"


def fbytes(value: float | None) -> str:
    """Bytes for humans. The CSV keeps the exact byte count."""
    if value is None:
        return ""
    if value >= 1048576.0:
        return f"{value / 1048576.0:.2f} MB"
    if value >= 1024.0:
        return f"{value / 1024.0:.1f} KB"
    return f"{value:.0f} B"


def fcount(value: float | None) -> str:
    if value is None:
        return ""
    return f"{value:,.0f}"


def read_float(row: dict, key: str) -> float | None:
    """Empty cell means 'not measured' and stays None; it must never become zero."""
    text = (row.get(key) or "").strip()
    if text == "":
        return None
    try:
        return float(text)
    except ValueError:
        return None


class Point:
    """One (agent_count, techniques) data point and the runs that measured it."""

    def __init__(self, agents: int, techniques: str) -> None:
        self.agents = agents
        self.techniques = techniques
        self.rows: list[dict] = []

    def per_run(self, key: str) -> list[float]:
        values = [read_float(r, key) for r in self.rows]
        return [v for v in values if v is not None]

    def summary(self, key: str) -> tuple[float | None, float | None, float | None]:
        """(median across runs, min across runs, max across runs) of a per-run column."""
        values = self.per_run(key)
        if not values:
            return None, None, None
        return median(values), min(values), max(values)


def load_points(csv_paths: list[Path], allow_editor: bool) -> tuple[list[Point], dict]:
    """Load one or more summary CSVs into data points.

    Several CSVs may be combined -- a sweep is often split into a coarse pass and a finer one around
    an interesting region -- but only if they describe the same environment, which is checked below.
    """
    rows: list[dict] = []
    for csv_path in csv_paths:
        with csv_path.open(newline="", encoding="utf-8") as handle:
            part = list(csv.DictReader(handle))
        if not part:
            raise SystemExit(f"{csv_path}: no rows")
        required = {"agent_count", "techniques", "frame_ms_median", "step_ms_median"}
        missing = required - set(part[0].keys())
        if missing:
            raise SystemExit(f"{csv_path}: missing expected columns: {sorted(missing)}")
        rows.extend(part)

    eligible, refused = [], []
    for row in rows:
        why = []
        if row.get("build_type") != "Player":
            why.append(f"build_type={row.get('build_type')}")
        if row.get("is_batchmode") == "1":
            why.append("is_batchmode=1")
        if row.get("is_development_build") == "1":
            why.append("is_development_build=1")
        if why and not allow_editor:
            refused.append((row, "; ".join(why)))
        else:
            eligible.append(row)

    if refused and not allow_editor:
        print(f"  refused {len(refused)} row(s) that are not release player measurements:", file=sys.stderr)
        for row, why in refused[:5]:
            print(f"    agents={row.get('agent_count')} run={row.get('run')}: {why}", file=sys.stderr)
        if not eligible:
            raise SystemExit(
                "No release player rows in this CSV. Editor and batch-mode rows are not results "
                "(see docs/METHOD.md section 1). Pass --allow-editor to tabulate them anyway."
            )

    # Anything that would make two rows incomparable must not end up in one table.
    for column, explanation in (
        ("scripting_backend", "Mono and IL2CPP timings are not comparable"),
        ("render_pipeline", "render pipelines are not comparable"),
        ("cpu", "rows from different CPUs are not comparable"),
        ("gpu", "rows from different GPUs are not comparable"),
        ("screen", "rendering cost depends on resolution"),
        ("seed", "a different seed is a different simulation"),
        ("fixed_timestep_s", "a different timestep is a different workload"),
        ("max_steps_per_frame", "a different step cap is a different workload"),
        ("measured_frames", "percentiles over different window lengths are not comparable"),
        ("stepping_mode", "rows stepped under different rules measure different amounts of work per frame"),
        ("allocation_source", "allocation figures from different counters mean different things"),
    ):
        # A row that lacks the column entirely is treated as its own distinct value, not skipped.
        # Otherwise a CSV written before the column existed merges silently with one written after,
        # which is exactly the case the check is here to catch.
        values = {(r[column] if column in r and r[column] is not None else "(column absent)") for r in eligible}
        if len(values) > 1:
            raise SystemExit(f"These rows mix {column} {sorted(values)}: {explanation}.")

    points: dict[tuple[int, str], Point] = {}
    for row in eligible:
        key = (int(row["agent_count"]), row.get("techniques", ""))
        points.setdefault(key, Point(*key)).rows.append(row)

    first = eligible[0]
    meta = {
        "unity_version": first.get("unity_version", ""),
        "scripting_backend": first.get("scripting_backend", ""),
        "render_pipeline": first.get("render_pipeline", ""),
        "build_type": first.get("build_type", ""),
        "cpu": first.get("cpu", ""),
        "gpu": first.get("gpu", ""),
        "operating_system": first.get("operating_system", ""),
        "screen": first.get("screen", ""),
        "vsync_count": first.get("vsync_count", ""),
        "target_frame_rate": first.get("target_frame_rate", ""),
        "display_refresh_hz": first.get("display_refresh_hz", ""),
        "seed": first.get("seed", ""),
        "measured_frames": first.get("measured_frames", ""),
        "warmup_frames": first.get("warmup_frames", ""),
        "eligible_rows": len(eligible),
        "refused_rows": len(refused),
    }
    ordered = sorted(points.values(), key=lambda p: (p.techniques != "baseline", p.techniques, p.agents))
    return ordered, meta


def build_table(points: list[Point], csv_name: str) -> str:
    header = (
        "| Agents | Techniques | Runs | Frame ms (median) | Frame ms (run spread) | "
        "Frame ms (p95) | Sim step ms (median) | Sim step ms (p95) | GC alloc / frame | "
        "Draw calls | SetPass calls |"
    )
    rule = (
        "|-------:|------------|-----:|------------------:|:----------------------|"
        "---------------:|---------------------:|--------------------:|-----------------:|"
        "-----------:|--------------:|"
    )
    lines = [header, rule]
    for point in points:
        frame_med, frame_lo, frame_hi = point.summary("frame_ms_median")
        frame_p95, _, _ = point.summary("frame_ms_p95")
        step_med, _, _ = point.summary("step_ms_median")
        step_p95, _, _ = point.summary("step_ms_p95")
        gc_med, _, _ = point.summary("gc_alloc_bytes_median")
        draw_med, _, _ = point.summary("draw_calls_median")
        setpass_med, _, _ = point.summary("setpass_calls_median")

        spread = ""
        if frame_lo is not None and frame_hi is not None:
            spread = f"{fnum(frame_lo)} – {fnum(frame_hi)}"

        lines.append(
            f"| {point.agents:,} | {point.techniques} | {len(point.rows)} | {fnum(frame_med)} | "
            f"{spread} | {fnum(frame_p95)} | {fnum(step_med)} | {fnum(step_p95)} | "
            f"{fbytes(gc_med)} | {fcount(draw_med)} | {fcount(setpass_med)} |"
        )
    lines.append("")
    lines.append(GENERATED_NOTE.format(csv=csv_name))
    return "\n".join(lines)


def build_crossing(points: list[Point], csv_name: str) -> str:
    """Report where the measured medians bracket each budget, per technique. Never interpolates."""
    techniques = sorted({p.techniques for p in points}, key=lambda t: (t != "baseline", t))
    if not techniques:
        return "No rows in " + csv_name + "."
    blocks = []
    for technique in techniques:
        body = _crossing_for(points, technique)
        blocks.append(f"**{technique}**\n\n{body}" if len(techniques) > 1 else body)
    return "\n\n".join(blocks)


def _crossing_for(points: list[Point], technique: str) -> str:
    lines = []
    selected = sorted([p for p in points if p.techniques == technique], key=lambda p: p.agents)

    measured = []
    for point in selected:
        med, _, _ = point.summary("frame_ms_median")
        if med is not None:
            measured.append((point.agents, med))
    if not measured:
        return f"- No frame-time medians recorded for {technique}."

    for label, budget in (("16.7 ms (60 fps)", BUDGET_60_MS), ("33.3 ms (30 fps)", BUDGET_30_MS)):
        below = [(a, m) for a, m in measured if m <= budget]
        above = [(a, m) for a, m in measured if m > budget]
        if not above:
            top = max(measured, key=lambda t: t[0])
            lines.append(
                f"- **{label}** — not crossed at any measured agent count. The largest measured "
                f"point, {top[0]:,} agents, has a median frame time of {top[1]:.2f} ms."
            )
        elif not below:
            first = min(above, key=lambda t: t[0])
            lines.append(
                f"- **{label}** — already exceeded at the smallest measured agent count, "
                f"{first[0]:,} agents ({first[1]:.2f} ms). The crossing is below the measured range."
            )
        else:
            last_below = max(below, key=lambda t: t[0])
            first_above = min(above, key=lambda t: t[0])
            lines.append(
                f"- **{label}** — crossed between **{last_below[0]:,} agents** ({last_below[1]:.2f} ms) "
                f"and **{first_above[0]:,} agents** ({first_above[1]:.2f} ms). "
                f"The sweep does not sample between those two counts, so the exact crossing point is "
                f"bracketed, not measured."
            )
    return "\n".join(lines)


def replace_between(text: str, begin: str, end: str, body: str, path: Path) -> str:
    start = text.find(begin)
    stop = text.find(end)
    if start == -1 or stop == -1:
        raise SystemExit(f"{path}: markers {begin} / {end} not found")
    if stop < start:
        raise SystemExit(f"{path}: marker {end} appears before {begin}")
    return text[: start + len(begin)] + "\n\n" + body + "\n\n" + text[stop:]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--csv", required=True, type=Path, nargs="+",
                        help="benchmark summary CSV(s); several are combined if they share an environment")
    parser.add_argument("--readme", type=Path, default=Path("README.md"))
    parser.add_argument("--allow-editor", action="store_true", help="tabulate non-player rows (not results)")
    parser.add_argument("--check", action="store_true", help="exit 1 if the README is not up to date")
    args = parser.parse_args()

    points, meta = load_points(args.csv, args.allow_editor)
    csv_name = ", ".join(p.as_posix() for p in args.csv)
    table = build_table(points, csv_name)
    crossing = build_crossing(points, csv_name)

    original = args.readme.read_text(encoding="utf-8")
    updated = replace_between(original, TABLE_BEGIN, TABLE_END, table, args.readme)
    updated = replace_between(updated, BUDGET_BEGIN, BUDGET_END, crossing, args.readme)

    if args.check:
        if updated != original:
            print("README results table is out of date.", file=sys.stderr)
            return 1
        print("README results table is up to date.")
        return 0

    args.readme.write_text(updated, encoding="utf-8", newline="\n")
    print(f"Wrote {len(points)} data point(s) from {csv_name} into {args.readme}:")
    print(f"  {meta['build_type']} · {meta['scripting_backend']} · {meta['render_pipeline']} RP · Unity {meta['unity_version']}")
    print(f"  {meta['cpu']} · {meta['gpu']} · {meta['screen']}")
    print(f"  vsync={meta['vsync_count']} targetFrameRate={meta['target_frame_rate']} refresh={meta['display_refresh_hz']}Hz")
    print(f"  {meta['eligible_rows']} eligible row(s), {meta['refused_rows']} refused")
    for point in points:
        med, lo, hi = point.summary("frame_ms_median")
        print(f"  {point.agents:>7,} agents · {len(point.rows)} runs · frame median {fnum(med)} ms (spread {fnum(lo)}–{fnum(hi)})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
